title: Zámky jižní Moravy
baseURL: https://jirka941.github.io/hugo-start/
languageCode: cs-cz
publishDir: docs
googleAnalytics: UA-117923046-1

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Průvodce historií zámků na jižní Moravě.
  authors: Authors

